---
- name: Validate nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  listen: Reload nginx

- name: Reload nginx service
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: Reload nginx
